//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentChallenge.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevelopmentChallenge.Data.Resources.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area {0}.
        /// </summary>
        internal static string AreaTotal {
            get {
                return ResourceManager.GetString("AreaTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Reporte de Formas&lt;/h1&gt;.
        /// </summary>
        internal static string Cabecera {
            get {
                return ResourceManager.GetString("Cabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Círculo|Círculos.
        /// </summary>
        internal static string Circulo {
            get {
                return ResourceManager.GetString("Circulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrado|Cuadrados.
        /// </summary>
        internal static string Cuadrado {
            get {
                return ResourceManager.GetString("Cuadrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} | Area {2} | Perímetro {3} &lt;br/&gt;.
        /// </summary>
        internal static string LineaCuerpo {
            get {
                return ResourceManager.GetString("LineaCuerpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Lista vacía de formas!&lt;/h1&gt;.
        /// </summary>
        internal static string ListaVacia {
            get {
                return ResourceManager.GetString("ListaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perímetro {0} .
        /// </summary>
        internal static string PerimetroTotal {
            get {
                return ResourceManager.GetString("PerimetroTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectángulo|Rectánculos.
        /// </summary>
        internal static string Rectangulo {
            get {
                return ResourceManager.GetString("Rectangulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} formas .
        /// </summary>
        internal static string TotalFormas {
            get {
                return ResourceManager.GetString("TotalFormas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL:&lt;br/&gt; .
        /// </summary>
        internal static string TotalPie {
            get {
                return ResourceManager.GetString("TotalPie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapecio|Trapecios.
        /// </summary>
        internal static string Trapecio {
            get {
                return ResourceManager.GetString("Trapecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triángulo|Triángulos.
        /// </summary>
        internal static string TrianguloEquilatero {
            get {
                return ResourceManager.GetString("TrianguloEquilatero", resourceCulture);
            }
        }
    }
}
